[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ps_1loop"
version = "0.3.0"
authors = [
  {name = "Yosuke Kobayashi", email = "yosukekobayashi@arizona.edu"},
]
description = "Theory code for galaxy power spectrum based on one-loop perturbation theory"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "sympy>=1.11.0",
    "jax==0.4.28",
    "jaxlib==0.4.28",
    "quadax",
    "interpax"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
tests = [
  'pytest',
  'tomllib',
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ps_1loop = ["pt_matrix/*/*/*.txt"]

[project.urls]
Homepage = "https://github.com/archaeo-pteryx/ps_1loop"
