[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "elf"
version = "0.1.0"
authors = [
  {name = "Yosuke Kobayashi", email = "yosuke.kobayashi@cc.kyoto-su.ac.jp"},
]
description = "Theory code for galaxy power spectrum based on one-loop perturbation theory"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "sympy>=1.11.0",
    "jax>=0.4.26",
    "jaxlib>=0.4.26",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
tests = [
  'pytest',
  'tomllib',
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
elf = ["pt_matrix/*/*/*.txt", "pt_coeff/*.txt"]

[project.urls]
Homepage = "https://github.com/archaeo-pteryx/elf"
